spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  application:
    name: coupon-service
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
coupon-service:
  external:
    country:
      url: https://api.country.is