CREATE TABLE COUPON
(
    CODE           VARCHAR_IGNORECASE PRIMARY KEY,
    USAGE_LIMIT    INTEGER   DEFAULT 100               NOT NULL,
    USAGE_COUNT    INTEGER   DEFAULT 0                 NOT NULL,
    TARGET_COUNTRY VARCHAR                             NOT NULL,
    CREATED_AT     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);